// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Vla8islav/gophemart/internal/domain (interfaces: GophemartRepository,GophemartService)
//
// Generated by this command:
//
//	mockgen -destination=domain_mock.go -package=mocks github.com/Vla8islav/gophemart/internal/domain GophemartRepository,GophemartService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Vla8islav/gophemart/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockGophemartRepository is a mock of GophemartRepository interface.
type MockGophemartRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGophemartRepositoryMockRecorder
	isgomock struct{}
}

// MockGophemartRepositoryMockRecorder is the mock recorder for MockGophemartRepository.
type MockGophemartRepositoryMockRecorder struct {
	mock *MockGophemartRepository
}

// NewMockGophemartRepository creates a new mock instance.
func NewMockGophemartRepository(ctrl *gomock.Controller) *MockGophemartRepository {
	mock := &MockGophemartRepository{ctrl: ctrl}
	mock.recorder = &MockGophemartRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGophemartRepository) EXPECT() *MockGophemartRepositoryMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockGophemartRepository) CreateUser(ctx context.Context, user domain.CreateUserParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockGophemartRepositoryMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockGophemartRepository)(nil).CreateUser), ctx, user)
}

// GetUserByLogin mocks base method.
func (m *MockGophemartRepository) GetUserByLogin(ctx context.Context, login string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLogin", ctx, login)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByLogin indicates an expected call of GetUserByLogin.
func (mr *MockGophemartRepositoryMockRecorder) GetUserByLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLogin", reflect.TypeOf((*MockGophemartRepository)(nil).GetUserByLogin), ctx, login)
}

// Ping mocks base method.
func (m *MockGophemartRepository) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockGophemartRepositoryMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockGophemartRepository)(nil).Ping), ctx)
}

// MockGophemartService is a mock of GophemartService interface.
type MockGophemartService struct {
	ctrl     *gomock.Controller
	recorder *MockGophemartServiceMockRecorder
	isgomock struct{}
}

// MockGophemartServiceMockRecorder is the mock recorder for MockGophemartService.
type MockGophemartServiceMockRecorder struct {
	mock *MockGophemartService
}

// NewMockGophemartService creates a new mock instance.
func NewMockGophemartService(ctrl *gomock.Controller) *MockGophemartService {
	mock := &MockGophemartService{ctrl: ctrl}
	mock.recorder = &MockGophemartServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGophemartService) EXPECT() *MockGophemartServiceMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockGophemartService) CreateUser(ctx context.Context, request domain.UserRegisterRequest) (*domain.AuthResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, request)
	ret0, _ := ret[0].(*domain.AuthResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockGophemartServiceMockRecorder) CreateUser(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockGophemartService)(nil).CreateUser), ctx, request)
}

// LoginUser mocks base method.
func (m *MockGophemartService) LoginUser(ctx context.Context, request domain.UserLoginRequest) (*domain.AuthResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginUser", ctx, request)
	ret0, _ := ret[0].(*domain.AuthResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginUser indicates an expected call of LoginUser.
func (mr *MockGophemartServiceMockRecorder) LoginUser(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUser", reflect.TypeOf((*MockGophemartService)(nil).LoginUser), ctx, request)
}

// Ping mocks base method.
func (m *MockGophemartService) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockGophemartServiceMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockGophemartService)(nil).Ping), ctx)
}
