// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Vla8islav/gophemart/internal/domain (interfaces: GophermartRepository,GophemartService,GophermartAccrualClient)
//
// Generated by this command:
//
//	mockgen -destination=domain_mock.go -package=mocks github.com/Vla8islav/gophemart/internal/domain GophermartRepository,GophemartService,GophermartAccrualClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Vla8islav/gophemart/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockGophemartRepository is a mock of GophermartRepository interface.
type MockGophemartRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGophemartRepositoryMockRecorder
	isgomock struct{}
}

// MockGophemartRepositoryMockRecorder is the mock recorder for MockGophemartRepository.
type MockGophemartRepositoryMockRecorder struct {
	mock *MockGophemartRepository
}

// NewMockGophemartRepository creates a new mock instance.
func NewMockGophemartRepository(ctrl *gomock.Controller) *MockGophemartRepository {
	mock := &MockGophemartRepository{ctrl: ctrl}
	mock.recorder = &MockGophemartRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGophemartRepository) EXPECT() *MockGophemartRepositoryMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockGophemartRepository) CreateOrder(ctx context.Context, userID int64, orderNumber string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, userID, orderNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockGophemartRepositoryMockRecorder) CreateOrder(ctx, userID, orderNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockGophemartRepository)(nil).CreateOrder), ctx, userID, orderNumber)
}

// CreateUser mocks base method.
func (m *MockGophemartRepository) CreateUser(ctx context.Context, user domain.CreateUserParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockGophemartRepositoryMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockGophemartRepository)(nil).CreateUser), ctx, user)
}

// GetUserBalance mocks base method.
func (m *MockGophemartRepository) GetUserBalance(ctx context.Context, userID int64) (*domain.UserBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBalance", ctx, userID)
	ret0, _ := ret[0].(*domain.UserBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBalance indicates an expected call of GetUserBalance.
func (mr *MockGophemartRepositoryMockRecorder) GetUserBalance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBalance", reflect.TypeOf((*MockGophemartRepository)(nil).GetUserBalance), ctx, userID)
}

// GetUserByLogin mocks base method.
func (m *MockGophemartRepository) GetUserByLogin(ctx context.Context, login string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLogin", ctx, login)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByLogin indicates an expected call of GetUserByLogin.
func (mr *MockGophemartRepositoryMockRecorder) GetUserByLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLogin", reflect.TypeOf((*MockGophemartRepository)(nil).GetUserByLogin), ctx, login)
}

// Ping mocks base method.
func (m *MockGophemartRepository) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockGophemartRepositoryMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockGophemartRepository)(nil).Ping), ctx)
}

// MockGophemartService is a mock of GophemartService interface.
type MockGophemartService struct {
	ctrl     *gomock.Controller
	recorder *MockGophemartServiceMockRecorder
	isgomock struct{}
}

// MockGophemartServiceMockRecorder is the mock recorder for MockGophemartService.
type MockGophemartServiceMockRecorder struct {
	mock *MockGophemartService
}

// NewMockGophemartService creates a new mock instance.
func NewMockGophemartService(ctrl *gomock.Controller) *MockGophemartService {
	mock := &MockGophemartService{ctrl: ctrl}
	mock.recorder = &MockGophemartServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGophemartService) EXPECT() *MockGophemartServiceMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockGophemartService) CreateOrder(ctx context.Context, userID int64, orderNumber string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, userID, orderNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockGophemartServiceMockRecorder) CreateOrder(ctx, userID, orderNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockGophemartService)(nil).CreateOrder), ctx, userID, orderNumber)
}

// CreateUser mocks base method.
func (m *MockGophemartService) CreateUser(ctx context.Context, request domain.UserRegisterRequest) (*domain.AuthResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, request)
	ret0, _ := ret[0].(*domain.AuthResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockGophemartServiceMockRecorder) CreateUser(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockGophemartService)(nil).CreateUser), ctx, request)
}

// GetUserBalance mocks base method.
func (m *MockGophemartService) GetUserBalance(ctx context.Context, userID int64) (*domain.UserBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBalance", ctx, userID)
	ret0, _ := ret[0].(*domain.UserBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBalance indicates an expected call of GetUserBalance.
func (mr *MockGophemartServiceMockRecorder) GetUserBalance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBalance", reflect.TypeOf((*MockGophemartService)(nil).GetUserBalance), ctx, userID)
}

// LoginUser mocks base method.
func (m *MockGophemartService) LoginUser(ctx context.Context, request domain.UserLoginRequest) (*domain.AuthResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginUser", ctx, request)
	ret0, _ := ret[0].(*domain.AuthResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginUser indicates an expected call of LoginUser.
func (mr *MockGophemartServiceMockRecorder) LoginUser(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUser", reflect.TypeOf((*MockGophemartService)(nil).LoginUser), ctx, request)
}

// Ping mocks base method.
func (m *MockGophemartService) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockGophemartServiceMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockGophemartService)(nil).Ping), ctx)
}

// MockGophermartAccrualClient is a mock of GophermartAccrualClient interface.
type MockGophermartAccrualClient struct {
	ctrl     *gomock.Controller
	recorder *MockGophermartAccrualClientMockRecorder
	isgomock struct{}
}

// MockGophermartAccrualClientMockRecorder is the mock recorder for MockGophermartAccrualClient.
type MockGophermartAccrualClientMockRecorder struct {
	mock *MockGophermartAccrualClient
}

// NewMockGophermartAccrualClient creates a new mock instance.
func NewMockGophermartAccrualClient(ctrl *gomock.Controller) *MockGophermartAccrualClient {
	mock := &MockGophermartAccrualClient{ctrl: ctrl}
	mock.recorder = &MockGophermartAccrualClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGophermartAccrualClient) EXPECT() *MockGophermartAccrualClientMockRecorder {
	return m.recorder
}

// GetOrderInfo mocks base method.
func (m *MockGophermartAccrualClient) GetOrderInfo(ctx context.Context, orderNumber string) (*domain.AccrualOrderInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderInfo", ctx, orderNumber)
	ret0, _ := ret[0].(*domain.AccrualOrderInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderInfo indicates an expected call of GetOrderInfo.
func (mr *MockGophermartAccrualClientMockRecorder) GetOrderInfo(ctx, orderNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderInfo", reflect.TypeOf((*MockGophermartAccrualClient)(nil).GetOrderInfo), ctx, orderNumber)
}
